spring:
  application:
    name: skillswap
  cache:
    type: redis
  data:
    redis:
      host: redis-container
      port: 6379
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://mysql-container:3306/mydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    level: TRACE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

