spring:
  application:
    name: skillswap
  cache:
    type: redis
  data:
    redis:
      host: ${redis_host}
      port:${redis_port}
  main:
    allow-circular-references: true
  datasource:
    url: ${mysql_url}
    username: ${mysql_username}
    password: ${mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    level: TRACE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

